// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace mygame
{
public static class GPGSIDs
{
        public const string achievement_no_pal_shall_be_ditched = "CgkI__bt5ooSEAIQDQ"; // <GPGSID>
        public const string leaderboard_world_one_leaderboard = "CgkI__bt5ooSEAIQDg"; // <GPGSID>
        public const string achievement_combo_jumbo = "CgkI__bt5ooSEAIQCw"; // <GPGSID>
        public const string achievement_this_time_its_personal = "CgkI__bt5ooSEAIQEw"; // <GPGSID>
        public const string leaderboard_world_three_leaderboard = "CgkI__bt5ooSEAIQGA"; // <GPGSID>
        public const string leaderboard_world_four_leaderboard = "CgkI__bt5ooSEAIQGQ"; // <GPGSID>
        public const string package_name = "com.SIDM.AcidTrip"; // <GPGSID>
        public const string achievement_crash_n_burn = "CgkI__bt5ooSEAIQBQ"; // <GPGSID>
        public const string achievement_no_blood_shall_spill = "CgkI__bt5ooSEAIQFA"; // <GPGSID>
        public const string achievement_acid_tripped = "CgkI__bt5ooSEAIQEA"; // <GPGSID>
        public const string achievement_first_blood = "CgkI__bt5ooSEAIQAg"; // <GPGSID>
        public const string leaderboard_world_five_leaderboard = "CgkI__bt5ooSEAIQGg"; // <GPGSID>
        public const string leaderboard_world_two_leaderboard = "CgkI__bt5ooSEAIQDw"; // <GPGSID>
        public const string achievement_trigger_happy = "CgkI__bt5ooSEAIQAw"; // <GPGSID>
        public const string achievement_privates_impression = "CgkI__bt5ooSEAIQBA"; // <GPGSID>
        public const string achievement_prejudiced = "CgkI__bt5ooSEAIQFQ"; // <GPGSID>
        public const string achievement_first_path = "CgkI__bt5ooSEAIQAQ"; // <GPGSID>
        public const string achievement_burned = "CgkI__bt5ooSEAIQCQ"; // <GPGSID>
        public const string achievement_magazine_cover_boy = "CgkI__bt5ooSEAIQCg"; // <GPGSID>
        public const string achievement_shootsavescore = "CgkI__bt5ooSEAIQFw"; // <GPGSID>
        public const string achievement_knowledge_is_power = "CgkI__bt5ooSEAIQEg"; // <GPGSID>
        public const string achievement_sergeants_mark = "CgkI__bt5ooSEAIQDA"; // <GPGSID>
        public const string achievement_akombo = "CgkI__bt5ooSEAIQFg"; // <GPGSID>
        public const string achievement_overdosed = "CgkI__bt5ooSEAIQEQ"; // <GPGSID>

}
}
